### PR TITLE
[FIX] Do not apply filters if input data is not present.

### LINKED ISSUE #80: Gene Set Enrichment crashes when no data and typing in filter field
When Gene Set Enrichment is empty and there is no data on the input, any change in the filter entry box crashes the widget. 

It would also help that when there is no data on the input, the widget would display "(no data on input)" in the Info box.

### LINKED ISSUE #81: Gene Name Matcher crashes when no data and typing in filter field
When Gene Name Matcher is empty and there is no data on the input, any change in the filter entry box crashes the widget.

It would also help that when there is no data on the input, the widget would display "(no data on input)" in the Info box.

### PR DESCRIPTION
**Pull request by JakaKokosar**
##### Issue
Fixes #81 
Fixes #80 

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by JakaKokosar** [comment]
@BlazZupan Can you check if everything is OK after applying this changes?

**Comment by BlazZupan** [comment]
The problem is still there, now in some other form. Take file widget, use it to open Iris data set, feed it into Gene Name Matcher, then write something in filter and delete to get an empty line. Here is a trace:

```Traceback (most recent call last):
  File "/Users/blaz/Documents/dev/orange3/Orange/widgets/gui.py", line 2318, in __call__
    self.func(**kwds)
  File "/Users/blaz/Documents/dev/orange3-bioinformatics/orangecontrib/bioinformatics/widgets/OWGeneNameMatcher.py", line 317, in apply_filter
    self.table_model.show_table(str(self.search_pattern))
  File "/Users/blaz/Documents/dev/orange3-bioinformatics/orangecontrib/bioinformatics/widgets/OWGeneNameMatcher.py", line 135, in show_table
    self.wrap(self.data_table[self.filter_table(filter_pattern)])
  File "/Users/blaz/Documents/dev/orange3-bioinformatics/orangecontrib/bioinformatics/widgets/OWGeneNameMatcher.py", line 121, in filter_table
    _, col_size = self.data_table.shape
AttributeError: 'NoneType' object has no attribute 'shape'```

**Comment by JakaKokosar** [comment]
@BlazZupan , thanks! This should be fixed. Can you confirm?

**Comment by BlazZupan** [comment]
Fixed now, thanks.

**Pull request merged**
