### PR TITLE
[ENH] OWClusterAnalysis: add support for multiple discrete variables selection

### PR DESCRIPTION
**Pull request by JakaKokosar**
Resolves this issue:
https://github.com/biolab/orange3-single-cell/issues/299

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by JakaKokosar** [comment]
@mstrazar can you test this? I expect there will still be some issues...

**Comment by JakaKokosar** [comment]
@BlazZupan Can you look at it also?

**Comment by mstrazar** [comment]
Results appear to be dependent on the order the variables are clicked; test workflow here:
[test-workflow-ca.ows.zip](https://github.com/biolab/orange3-bioinformatics/files/2467950/test-workflow-ca.ows.zip)

Replicate first, Type second:
replicate-first_type-second

Type first, Replicate second:
type-first_replicate-second

**Comment by JakaKokosar** [comment]
Thanks, I have fixed this problem. Can you test again?

**Comment by mstrazar** [comment]
Looks good now!

Only 1 remaining minor issue: widget is now too big to fit on a laptop screen, so perhaps we can resize Cluster Indicator and/or Gene Sets frames?

**Pull request merged**
