### PR TITLE
[ENH] OWGeneNameMatcher: revision

### LINKED ISSUE #77: Gene Name Matcher: revision
Here is a request for a revision of user interface used by Gene Name Matcher widget that would better expose gene names and allow selection of the subset of input data.

screen shot 2018-07-18 at 10 48 36

- "Stored in data column" is disabled if no suitable data column exists (categorical or text feature)
- In Stored in data column drop down include only features with enough diversity of names (say, take a sample of 1000 data instances, the most frequent item should not be repeated more than 10 times)
- Exclude unmatched genes is disabled if all gene IDs are matched
- Replace feature IDs constructs a table with feature names that correspond to gene (symbol) names. If gene is not matched and we do not exclude unmatched gene, the feature name is copied from the input
- Include gene description includes a column, or feature attribute with name "Description"
- Entrez IDs are included in column/feature attribute called "Entrez ID"
- Include all other available information includes "Type" (type of gene, text), "Synonyms" (a text field with synonims), "UniProt" (ID, text), "dictyBase" (ID, text, if applicable)

Widget has one output (see Data Table for similar design):
- Data, data instances selected in the gene list table or data with selected columns (depending where the gene IDs are). If no current selection than ALL data instances/columns are on this output
- Genes, a table with complete gene information (include all info). Genes are in rows. The table is in constitution similar to that shown in the widget, but includes ALL genes from the input. There is a another column (meta, discrete) with values Matched|Unmatched|Match Conflict. When no genes are matched, this output is None (to avoid construction of large data table where user has not set the right parameters yet).

### PR DESCRIPTION
**Pull request by JakaKokosar**
##### Issue
Fixes #77 

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by BlazZupan** [comment]
Works well, in a few first tests on data from Dictyostelium and a number of data sets from GEO. Will run some more tests with some other organisms and gene encodings.

**Comment by JakaKokosar** [comment]
@BlazZupan thanks to @ales-erjavec , this can now handles very large data sets.

**Comment by BlazZupan** [comment]
Auto commit should push new data after any change in the data table. Currently, auto-commit does not work. Also, when genes are selected in the table, only this selection of genes should be pushed to the output on the Genes channel (perhaps the initial idea was different, but after reviewing the widget I think only the selection of the genes should be on the output).

I was testing the widget on dicty data set with 12000 genes. It performs fine. There is, however, about 20s delay when the data is presented to the widget and the progress bar reaches 98%. Why, and can this be bypassed?

**Comment by JakaKokosar** [comment]
@BlazZupan 
> Auto commit should push new data after any change in the data table. Currently, auto-commit does not work.

Are you sure? I'm testing it now and it works as expected. Can you provide more information? 

> Also, when genes are selected in the table, only this selection of genes should be pushed to the output on the Genes channel (perhaps the initial idea was different, but after reviewing the widget I think only the selection of the genes should be on the output).

I'll change this ASAP.

> I was testing the widget on dicty data set with 12000 genes. It performs fine. There is, however, about 20s delay when the data is presented to the widget and the progress bar reaches 98%. Why, and can this be bypassed?

Results of the gene matcher must be transformed to a presentable data model. I have managed to speed up this process by pre-loading NCBI gene info. The delay should be a lot less noticeable now.

**Comment by JakaKokosar** [comment]
> Auto commit should push new data after any change in the data table. Currently, auto-commit does not work.
>>Are you sure? I'm testing it now and it works as expected. Can you provide more information?

Never mind, I found the problem. It should be working now.

**Comment by BlazZupan** [comment]
A minor error: do File -> Gene Name Matcher. Send Automatically should be on. Select a few genes in Gene Name Matcher. Now do Gene Name Matcher/Genes -> Data Table. Shown is a table with all genes, not just the selection. Then this is correctly updated when I perform another selection in Gene Name Matcher.

**Comment by BlazZupan** [comment]
Everything works, great. I have probably overtested on Dictyostelium, but used GEO datasets to check with other organisms as well.

**Pull request merged**
