### PR TITLE
[ENH] Rename to OWGeneNameMatcher to OWGenes, case insensitive filtering

### LINKED ISSUE #112: Gene Name Matcher: rename to Genes
##### Bioinformatics version
3.2.7

##### Proposed changes
Gene Name Matcher displays a list of genes that are present in the input data. While functionality of this widget is still shaping up, it is already fitting a role of a browser for genes. Currently, it has a very specific name while serving a more general purpose. I propose to rename to **Genes**, as the name is simpler and fits better the functionality of the current widget.

When renaming, make sure that the newly named widget works also with already existing workflows.

### LINKED ISSUE #113: Gene Name Matcher: filter by gene names
##### Bioinformatics version
3.2.7

##### Expected behavior
The filter should be applied to all the textual fields in the gene table, including to name and synonyms.

##### Actual behavior
The text in the filter is matched only to description (or so it looks like).

##### Steps to reproduce the behavior
File -> Gene Name Matcher. In File, choose brown-selected. Then type pre9 in the Filter box. The list in the table is empty, while it should include a gene pre9.

### PR DESCRIPTION
**Pull request by JakaKokosar**
##### Issue
Fixes #112
Fixes #113

##### Description of changes
Widget filters table rows across all columns. I've changed it so that is now case insensitive, this addresses issue #112.

screenshot 2019-02-20 at 10 54 51

screenshot 2019-02-20 at 10 54 42

Gene Name Matcher is renamed to Genes, as proposed in #113. I couldn't find any workflows in scOrange (that include this widget) to test if this change breaks anything. All links in the documentation were changed properly.

##### Includes
- [X] Code changes
- [ ] Tests
- [X] Documentation

### CODE REVIEW

**Comment by JakaKokosar** [comment]
@BlazZupan can you give this a quick look before merging? Thanks!

**Comment by BlazZupan** [comment]
@JakaKokosar can you please test if there are any workflows in single cell orange that included Gene Name Matcher and if there are, if they still run. Thanks.

**Comment by JakaKokosar** [comment]
As said, I have checked showcase workflows in scOrange and I can't find any. @mstrazar would know for sure. Can you please confirm?

**Comment by BlazZupan** [comment]
Any of the workflows that used Gene Name Matcher fails with:

UnknownWidgetDefinition('orangecontrib.bioinformatics.widgets.OWGeneNameMatcher.OWGeneNameMatcher')

Please change this PR so that it maintains, if possible, backward compatibility. I am attaching one workflow that was constructed with a current version of Orange and add-on and that fails upon loading:

[test.ows.zip](https://github.com/biolab/orange3-bioinformatics/files/2884816/test.ows.zip)

**Comment by JakaKokosar** [comment]
@BlazZupan we have added backward compatibility, this should be fixed now.

**Pull request merged**
