### PR TITLE
[NEW] Add kaplan-meier widget

### PR DESCRIPTION
**Pull request by JakaKokosar**
##### Issue
https://github.com/biolab/genialis/issues/4

##### Description of changes
Screenshot 2020-12-03 at 12 18 50

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by janezd** [comment]
Is there any reason why this should be in bioinformatics add-on and not in core widgets? KM is not specific to bioinformatics...

**Comment by BlazZupan** [comment]
This should perhaps go into a new survival analysis add-on.

**Comment by BlazZupan** [comment]
Looks great, though.

**Comment by JakaKokosar** [comment]
As discussed this will be in a separate widget

https://github.com/biolab/orange3-survival-analysis/pull/1

**Pull request closed without merging**
