### PR TITLE
[ENH] Update widget documentation and support markdown

### LINKED ISSUE #69: Docs: widgets documentation is out outdated
Since legacy [orange-bio](https://github.com/biolab/orange-bio) add-on, a lot has changed. For example, https://github.com/biolab/orange3-bioinformatics/pull/60 introduced GUI changes for some of the widgets. 

Some widgets are not supported anymore and others were completely re-designed, e.g., https://github.com/biolab/orange3-bioinformatics/pull/47

Documentation needs to be updated:

- [x] **Databases Update**
- [x] **dictyExpress** 
- [x] **Differential Expression** (new scoring method, https://github.com/biolab/orange3-bioinformatics/pull/29)
- [x] **Gene Info** -> is now Gene name matcher, https://github.com/biolab/orange3-bioinformatics/pull/47
- [x] **GO Browser** (organism and gene selection was removed)
- [x] **KEGG Pathways** (organism and gene selection was removed)

Documentation missing:

- [ ] **Gene Sets**
- [ ] **Set Enrichemnt** (https://github.com/biolab/orange3-bioinformatics/pull/67)

[Link to the documentation](https://github.com/biolab/orange3-bioinformatics/tree/master/doc)
[Read the Docs](https://orange3-bioinformatics.readthedocs.io/en/latest/)  -> #70

### PR DESCRIPTION
**Pull request by JakaKokosar**
##### Issue
Fixes #69 

##### Includes
- [ ] Code changes
- [ ] Tests
- [x] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
I have updated the documentation in a couple of ways. OSX adds a shadow in screenshots so I made images without shadow to save space. All images are also indexed and resized (excluding workflows). The template now somewhat emulates the one in core Orange, even though I could not include the stylesheet as Sphnix generates different html files for .rst and .md. I still think it is quite nice in terms of consistency.

**Comment by JakaKokosar** [comment]
Thank you, if @BlazZupan agrees we can merge this.

**Comment by ajdapretnar** [comment]
Let me just add the data.md.info file.

**Comment by ajdapretnar** [comment]
I have updated icons to the latest add-on status.
I have added two missing .md files for Cluster Analysis and Gene Set Enrichment. Could someone please write the documentation for this as I have no idea what they do? I have provided the image and the template already.
Finally, I added the data.md.info file to be used for parsing in hugo.

**Comment by ajdapretnar** [comment]
@nejc121 Could you please check the data.md.info file is ok?

**Comment by JakaKokosar** [comment]
@BlazZupan Can we merge this now?

**Pull request merged**
